version: 2

builds:
  - main: ./cmd/glive
    binary: glive
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/glive/cmd/glive/cmd.version={{.Version}}
      - -X github.com/glive/cmd/glive/cmd.commit={{.Commit}}
      - -X github.com/glive/cmd/glive/cmd.date={{.Date}}

archives:
  - formats: [tar.gz, zip]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  use: github
  groups:
    - title: Features
      regexp: "^feat"
    - title: Bug Fixes
      regexp: "^fix"
    - title: Security
      regexp: "^security"
